require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

# AllCops:
#   Exclude:
#     - spec/**/*

Rails/FindBy:
  Exclude:
    - app/helpers/application_helper.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'
  # IgnoredMethods: ['describe', 'context', 'it']