require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

Rails/FindBy:
  Exclude:
    - app/helpers/application_helper.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  IgnoredMethods: ['login']